spring:
  application:
    name: spring-web-basic

server:
  port: 8080

logging:
  level:
    com.codeit.springwebbasic.common.log.LogExample: debug
    org.springframework.web: warn
  file:
    name: /Users/taeeonkim/Desktop/study/codeit/logs/app.log
